In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/stjia/Documents/cloze-encounters/filedata/book-level.csv')

In [5]:
df.columns

Index(['index', 'gpt35_score', 'gpt4o_score', 'claude_score', 'llama8b_score',
       'llama70b_score', 'gemini_score', 'book_title', 'query_id', 'query',
       'book_id', 'correct_answer', 'in_books3', 'num_reviews', 'num_ratings',
       'avg_rating', 'genres', 'pub_year', 'author', 'isbn13', 'isbn10_v2',
       'isbn13_v2', 'fiction', 'nonfiction', 'count', 'popularity',
       'count_books', 'shares'],
      dtype='object')

In [6]:
score_cols = ['gpt35_score', 'gpt4o_score', 'claude_score', 'llama8b_score', 'llama70b_score', 'gemini_score']
avg_scores_by_books3 = df.groupby('in_books3')[score_cols].mean()
avg_scores_by_books3

,gpt35_score,gpt4o_score,claude_score,llama8b_score,llama70b_score,gemini_score
in_books3,,,,,,
False,0.122424,0.114536,0.152301,0.042838,0.161326,0.171449
True,0.115430,0.104896,0.133846,0.035130,0.139142,0.144871

In [7]:
# Calculate the average score across all models for each group in avg_scores_by_books3
avg_scores_by_books3['avg_model_score'] = avg_scores_by_books3[score_cols].mean(axis=1)
avg_scores_by_books3[['avg_model_score']]

           avg_model_score
in_books3
False             0.127479
True              0.112219